BANVETAU/BANVETAU/Areas/Admin/Controllers/AirportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BANVETAU.Common;
using BANVETAU.Models;

namespace BANVETAU.Areas.Admin.Controllers
{
    public class AirportController : BaseController
    {
        private BANVEMAYBAYEntities db = new BANVEMAYBAYEntities();
        // GET: Admin/Tickets
        public ActionResult Index()
        {
            var cities = db.cities.Where(m => m.status == 1).ToList();
            ViewBag.cities = cities;
            return View();
        }


        // GET: Admin/Tickets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ticket ticket = db.tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // GET: Admin/Tickets/Create
        public ActionResult Create()
        {
            var countries = db.countries.Where(m =>m.status == 1).ToList();
            ViewBag.countries = countries;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(country countries)
        {           
            //if(db.countries.Where(m=>m.countryName.Contains(countries.countryName)) == null)
            //    {
                    db.countries.Add(countries);
                    Message.set_flash("Successfully added Country", "success");
                    db.SaveChanges();
                    return RedirectToAction("Index");
                //}
                //else
                //{
                //    Message.set_flash("Country already exist", "danger");
                //    return View("Create");
                //}

            
        }

        //GET: Admin/Tickets/Create
        public ActionResult CreateCities()
        {
            var countries = db.countries.Where(m=>m.status == 1).ToList();
            ViewBag.countries = countries;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCities(city cities)
        {

            if (ModelState.IsValid)
            {
                db.cities.Add(cities);
                Message.set_flash("Successfully added Cities", "success");
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            Message.set_flash("More failed cities", "danger");
            return View("Create");
        }


        public ActionResult Status(int id)
        {
            city cities = db.cities.Find(id);
            cities.status = (cities.status == 1) ? 2 : 1;
            db.Entry(cities).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("Status change successful", "success");
            return RedirectToAction("Index");
        }
        //trash
        public ActionResult trash()
        {
            var list = db.cities.Where(m => m.status == 2).ToList();
            return View("Trash", list);
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult Deltrash(int id)
        {
            city morder = db.cities.Find(id);
            morder.status = 2;
            db.Entry(morder).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("Delete successfully", "success");
            return RedirectToAction("Index");
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult Retrash(int id)
        {
            city morder = db.cities.Find(id);
            morder.status = 1;
            db.Entry(morder).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("Successful recovery", "success");
            return RedirectToAction("trash");
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult deleteTrash(int id)
        {
            city morder = db.cities.Find(id);
            db.cities.Remove(morder);
            db.SaveChanges();
            Message.set_flash("Permanently deleted 1 Order", "success");
            return RedirectToAction("trash");
        }


    }
}

BANVETAU/BANVETAU/Areas/Admin/Views/Airport/Create.cshtml
@model BANVETAU.Models.country

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_layOutAdmin.cshtml";
}


<div class="card card-title bg-white p-1">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Manage Tickets </h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item"><a href="/Admin">Home</a></li>
                <li class="breadcrumb-item active">Manage Tickets</li>
            </ol>
        </div>
    </div>
</div>

<section class="card card-title bg-white p-1">
    @Html.Partial("_MessgeAlert")
    <div class="container bg-white pt-4 " style="margin-bottom:50px">

        @using (Html.BeginForm("Create", "Airport", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class=" row ">
                <div class="col-md-4">  </div>
                <div class="col-md-4"> <h3 class="text-center font-weight-bold text-success "> Add Country</h3> </div>
                <div class="col-md-4 ">
                    <div class="float-right">
                        <button class="btn btn-sm bg-success text-white"><i class="far fa-save"></i> Save</button>
                        <a href="~/admin/Airport" class="btn btn-sm bg-danger text-white"><i class="far fa-window-close"></i> Cancel</a>
                    </div>
                </div>
            </div>
            <div class=" row ">
                <div class="col-md-10">
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Country Name</span></label>
                        <input type="text" name="countryName" class="form-control" value="" required />
                    </div>                 
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Status</span></label>
                        <select name="status" class="selectpicker form-control" tabindex="1">
                            <option value="1">Display</option>
                            <option value="2">Hidden</option>
                        </select>
                    </div>
                </div>
             

            </div>
        }
    </div>
</section>

BANVETAU/BANVETAU/Areas/Admin/Views/Airport/CreateCities.cshtml
@model BANVETAU.Models.city

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_layOutAdmin.cshtml";
}


<div class="card card-title bg-white p-1">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Add Airport </h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item"><a href="/Admin">Home</a></li>
                <li class="breadcrumb-item active">Add Airport</li>
            </ol>
        </div>
    </div>
</div>

<section class="card card-title bg-white p-1">
    @Html.Partial("_MessgeAlert")
    <div class="container bg-white pt-4 "  style="margin-bottom:50px">

        @using (Html.BeginForm("CreateCities", "Airport", FormMethod.Post ))
        {
            @Html.AntiForgeryToken()
            <div class=" row ">
                <div class="col-md-4">  </div>
                <div class="col-md-4"> <h3 class="text-center font-weight-bold text-success "> Add Tickets</h3> </div>
                <div class="col-md-4 ">
                    <div class="float-right">
                        <button class="btn btn-sm bg-success text-white"><i class="far fa-save"></i> Save</button>
                        <a href="~/admin/Airport" class="btn btn-sm bg-danger text-white"><i class="far fa-window-close"></i> Cancel</a>
                    </div>
                </div>
            </div>
            <div class=" row ">
               
                <div class="col-md-10 ">


                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Country</span></label>
                        <select name="countryId" class="selectpicker form-control" tabindex="1">

                            @foreach (var item in ViewBag.countries)
                            {
                                <option value="@item.countryId">@item.countryName</option>
                            }

                        </select>
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">City Name</span></label>
                        <input type="text" name="cityName" class="form-control" value="" placeholder="CityName" required />

                    </div>

                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Status</span></label>
                        <select name="status" class="selectpicker form-control" tabindex="1">
                            <option value="1">Display</option>
                            <option value="2">Hidden</option>
                        </select>
                    </div>
                </div>

                </div>

           
        }
    </div>
</section>

BANVETAU/BANVETAU/Areas/Admin/Views/Airport/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layOutAdmin.cshtml";
}
<!-- Content Wrapper. Contains page content -->

<div class="card card-title bg-white p-1">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Quản Lý Lịch Trình </h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item m-0"><a href="~/Admin">Trang Chủ</a></li>

            </ol>
        </div>
    </div>
</div>
<section class="">
    <div class=" bg-white card  p-3">
        <div class="row justify-content-end">
            <div class="col-md-3">
                <div class=" pt-1 ml-9">
                    <a class="text-white btn btn-green" href="~/admin/Airport/Create">Thêm Ga</a>
                    <a class="text-white btn btn-green" href="~/admin/Airport/CreateCities">Thêm Vé</a>
                    <a class="text-white btn btn-danger" href="~/admin/Airport/trash">Lịch Sử Xóa</a>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-9  w-100 ">
                @Html.Partial("_MessgeAlert")
            </div>
            <div class="col-md-12 p-3">

                <table id="myTable1" class="table  table-striped table-bordered dt-responsive nowrap">
                    <thead>

                        <tr>
                            <th>Country</th>
                            <th>City</th>                            
                            <th>Function</th>
                            <th>Id</th>
                        </tr>

                    </thead>
                    <tbody>
                        @foreach (var item in ViewBag.cities)
                        { 
                        <tr>
                            <td style="font-size:14px;">@item.country.countryName</td>                          
                                <td style="font-size:14px;">@item.cityName</td>
                                <td>
                                    @if (item.status == 1)
                                    {
                                        <a class="btn btn-sm btn-light text-success border a33" href="@Url.Action("Status", "Airport", new { id = item.cityId })"> <i class="fas fa-toggle-on"></i> </a>
                                    }
                                    else
                                    {
                                        <a class="btn btn-sm btn-light text-danger border a33" href="@Url.Action("Status", "Airport", new { id = item.cityId})"> <i class="fas fa-toggle-off"></i> </a>
                                    }
                                    <a class="btn btn-sm btn-light text-danger border" href="@Url.Action("Deltrash", "Airport", new { id = item.cityId})"> <i class="fas fa-trash-alt"></i></a>

                                </td>
                                <td class="text-cam">@item.cityId</td>
                            
                        </tr>

                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</section>

BANVETAU/BANVETAU/Areas/Admin/Views/Airport/trash.cshtml
@model IEnumerable<BANVETAU.Models.city>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layOutAdmin.cshtml";
}
<!-- Content Wrapper. Contains page content -->

<div class="card card-title bg-white p-1">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Recycle Bin </h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item m-0"><a href="~/Admin">Home</a></li>
                <li class="breadcrumb-item active m-0">Recycle Bin</li>
            </ol>
        </div>
    </div>
</div>



<section class="">
    <div class=" bg-white card  p-3">
        <div class="row justify-content-end">
            <div class="col-md-3">
                <div class=" pt-1 ml-5">

                    <a class="text-white btn-sm btn-danger " href="~/admin/Airport">CANCEL</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-9  w-100 ">
                @Html.Partial("_MessgeAlert")
            </div>
            <div class="col-md-12 p-3">

                <table id="myTable1" class="table  table-striped table-bordered dt-responsive nowrap">
                    <thead>

                        <tr>
                            <th>Country</th>
                            <th>City</th>
                            <th>Function</th>
                            <th>Id</th>
                        </tr>

                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                        <td style="font-size:14px;">@item.country.countryName</td>

                        <td style="font-size:14px;">@item.cityName</td>
                        <td>
                            <a class="btn btn-sm btn-light text-dark border" href="@Url.Action("Retrash", "Airport", new { id = item.cityId })"> <i class="fas fa-undo"></i></a>
                            <a class="btn btn-sm btn-light text-danger border" href="@Url.Action("deleteTrash", "Airport", new { id = item.cityId })">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                        <td class="text-cam">@Html.DisplayFor(modelItem => item.cityId)</td>
                        </tr>
                    }
                        </tbody>

                    </table>
            </div>
        </div>
    </div>
</section>