BANVETAU/BANVETAU/Controllers/ModulesController.cs
using BanVeMayBay.Models;
using BANVETAU.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BANVETAU.Controllers
{
    public class ModulesController : Controller
    {
        // GET: Modules
        BANVEMAYBAYEntities db = new BANVEMAYBAYEntities();
        public ActionResult _Header()
        {
            if ((string)Session["userName11"] != "")
            {
                ViewBag.sessionFullname = Session["userName11"];
            }
            else
            {

            }
            return View("_Header");
        }
        public ActionResult _Mainmenu()
        {

            var list = db.menus.Where(m => m.status == 1 && m.parentid == 0).ToList();
            return View("_Mainmenu", list);
        }
        public ActionResult _Footer()
        {
            return View("_Footer");
        }

        public ActionResult Slider()
        {
            return View("Slider");
        }
        public ActionResult LogoSlide()
        {
            return View("LogoSlide");
        }
    }
}

BANVETAU/BANVETAU/Views/Shared/401.cshtml
@{

    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">

    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<div class="container card">
    <div class="card-body">
        <div class="alert alert-danger alert-dismissible">

            <h5><i class="icon fas fa-ban"></i> Notify!</h5>
            You do not have access!
        </div>
    </div>
</div>

BANVETAU/BANVETAU/Views/Shared/_LayOutSiteHeader.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zxx">


<!-- Mirrored from cyclonethemes.com/demo/html/yatra/flight.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 25 Dec 2019 17:22:12 GMT -->
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewBag.Title</title>
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="images/logo1.png">
    <!-- Bootstrap core CSS -->
    <link href="~/public/css/bootstrap.min.css" rel="stylesheet" type="text/css">

    <!--Custom CSS-->
    <link href="~/public/css/flight.css" rel="stylesheet" type="text/css">
    <!--Flaticons CSS-->
    <link href="font/flaticon.css" rel="stylesheet" type="text/css">
    <!--Plugin CSS-->
    <link href="~/public/css/plugin.css" rel="stylesheet" type="text/css">
    <!--Font Awesome-->
    <link href="~/Public/css/all.min.css" rel="stylesheet" />
    <script src="~/public/js/jquery-3.2.1.min.js"></script>

</head>
<body style="background-color: #FAFAFA;">

    <!-- Preloader -->
    <div id="preloader">
        <div id="status"></div>
    </div>
    <!-- Preloader Ends -->
    <!-- Header -->
    <header>
        @Html.Action("_Header", "Modules")

        <!-- Navigation Bar -->
        @Html.Action("_Mainmenu", "Modules")
        <!-- Navigation Bar Ends -->
    </header>
    <!-- Header Ends -->
    <!-- Slider -->
    @Html.Action("Slider", "Modules")
    <!-- End Slider -->
    @RenderBody()
    <!-- Top Destination Ends -->
    @Html.Action("LogoSlide", "Modules")
    <!-- Footer -->
    @Html.Action("_Footer", "Modules")
    <!-- Footer Ends -->
    <!-- Back to top start -->
    <div id="back-to-top">
        <a href="#"></a>
    </div>
    <!-- Back to top ends -->
    <!-- *Scripts* -->

    <script src="~/public/js/bootstrap.min.js"></script>
    <script src="~/public/js/plugin.js"></script>
    <script src="~/public/js/main.js"></script>
    <script src="~/public/js/custom-accordian.js"></script>
    <script src="~/public/js/preloader.js"></script>
</body>
</html>

BANVETAU/BANVETAU/Views/Shared/_MessgeAlert.cshtml
@using BANVETAU.Models
@if (Message.has_flash())
{
   MessageModel ms = Message.get_flash();
    <div class="float-left ">
        <p class=" text-@ms.msg_css "><span class="font-weight-bold"> Notify:</span> @ms.msg</p>
    </div>
}

BANVETAU/BANVETAU/Views/Shared/_layOutSite.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zxx">


<!-- Mirrored from cyclonethemes.com/demo/html/yatra/flight.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 25 Dec 2019 17:22:12 GMT -->
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Booking Train</title>
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="images/logo1.png">
    <!-- Bootstrap core CSS -->
    <link href="~/public/css/bootstrap.min.css" rel="stylesheet" type="text/css">

    <!--Custom CSS-->
    <link href="~/public/css/flight.css" rel="stylesheet" type="text/css">
    <!--Flaticons CSS-->
    <link href="font/flaticon.css" rel="stylesheet" type="text/css">
    <!--Plugin CSS-->
    <link href="~/public/css/plugin.css" rel="stylesheet" type="text/css">
    <!--Font Awesome-->
    <link href="~/Public/css/all.min.css" rel="stylesheet" />
    <script src="~/public/js/jquery-3.2.1.min.js"></script>
   
</head>
<body style="background-color: #FAFAFA;">

    <!-- Preloader -->
    <div id="preloader">
        <div id="status"></div>
    </div>
    <!-- Preloader Ends -->
    <!-- Header -->
    <header>
        @Html.Action("_Header", "Modules")

        <!-- Navigation Bar -->
        @Html.Action("_Mainmenu", "Modules")
        <!-- Navigation Bar Ends -->
    </header>
    <!-- Header Ends -->
   
    @RenderBody()
    <!-- Top Destination Ends -->
 
    <!-- Footer -->
    @Html.Action("_Footer", "Modules")
    <!-- Footer Ends -->
    <!-- Back to top start -->
    <div id="back-to-top">
        <a href="#"></a>
    </div>
    <!-- Back to top ends -->
    <!-- *Scripts* -->

    <script src="~/public/js/bootstrap.min.js"></script>
    <script src="~/public/js/plugin.js"></script>
    <script src="~/public/js/main.js"></script>
    <script src="~/public/js/custom-accordian.js"></script>
    <script src="~/public/js/preloader.js"></script>
</body>
</html>