BANVETAU/BANVETAU/Models/ticket.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BanVeMayBay.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ticket
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ticket()
    {

        this.ordersdetails = new HashSet<ordersdetail>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string flightCode { get; set; }

    public string airline { get; set; }

    public string ticketType { get; set; }

    public string img { get; set; }

    public Nullable<System.DateTime> departure_date { get; set; }

    public Nullable<int> guestTotal { get; set; }

    public Nullable<double> price { get; set; }

    public Nullable<double> priceSale { get; set; }

    public int Sold { get; set; }

    public System.DateTime created_at { get; set; }

    public int created_by { get; set; }

    public System.DateTime updated_at { get; set; }

    public int updated_by { get; set; }

    public int status { get; set; }

    public Nullable<System.TimeSpan> departure_time { get; set; }

    public Nullable<System.TimeSpan> arrival_time { get; set; }

    public Nullable<int> fromAirport { get; set; }

    public Nullable<int> toAirport { get; set; }



    public virtual city city { get; set; }

    public virtual city city1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ordersdetail> ordersdetails { get; set; }

}

}

BANVETAU/BANVETAU/Areas/Admin/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BANVETAU.Common;
using BANVETAU.Models;

namespace BANVETAU.Areas.Admin.Controllers
{
    public class TicketsController : BaseController
    {
        private BANVEMAYBAYEntities db = new BANVEMAYBAYEntities();

        // GET: Admin/Tickets
        public ActionResult Index()
        {
            
            var tickets = db.tickets.Where(m=>m.status == 1).ToList();
            ViewBag.tickets = tickets;
            
            return View();
        }

    
        // GET: Admin/Tickets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ticket ticket = db.tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // GET: Admin/Tickets/Create
        public ActionResult Create()
        {
            var cities = db.cities.ToList();
            ViewBag.cities = cities;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ticket ticket)
        {
            //ticket.flightCode = "NB_"+ticket.departure_date;
            ticket.img = "img.jpg";
            ticket.Sold = 0;
            if (ModelState.IsValid)
            {
                //HttpPostedFileBase file;
                //file = Request.Files["airline"];
                //string filename = "";
               // string ExtensionFile = Mystring.GetFileExtension(filename);
               // string namefilenew = Mystring.ToSlug(ticket.departure_date.Year.ToString())+ "." + ExtensionFile;
                //var path = Path.Combine(Server.MapPath("~/Public/images/flight"), filename);
                //file.SaveAs(path);
                ticket.airline = "";
                ticket.created_at = DateTime.Now;
                ticket.updated_at = DateTime.Now;
                ticket.created_by = int.Parse(Session["Admin_id"].ToString());
                ticket.updated_by = int.Parse(Session["Admin_id"].ToString());
                ticket.priceSale = ticket.price;
             
                db.tickets.Add(ticket);
                Message.set_flash("Successfully added ticket", "success");
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            Message.set_flash("More failed tickets", "danger");
            return View("Create");
        }
        

        public ActionResult Status(int id)
        {
            ticket tickets = db.tickets.Find(id);
            tickets.status = (tickets.status == 1) ? 2 : 1;
            db.Entry(tickets).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("Status change successful", "success");
            return RedirectToAction("Index");
        }
        //trash
        public ActionResult trash()
        {
            var list = db.tickets.Where(m => m.status == 0).ToList();
            return View("Trash", list);
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult Deltrash(int id)
        {
            ticket morder = db.tickets.Find(id);
           
            morder.status = 0;
            db.Entry(morder).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("Delete successfully", "success");
            return RedirectToAction("Index");
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult Retrash(int id)
        {
            ticket morder = db.tickets.Find(id);
            morder.status = 1;
            db.Entry(morder).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("Successful recovery", "success");
            return RedirectToAction("trash");
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult deleteTrash(int id)
        {
            ticket morder = db.tickets.Find(id);
            db.tickets.Remove(morder);
            db.SaveChanges();
            Message.set_flash("Permanently deleted 1 Order", "success");
            return RedirectToAction("trash");
        }
        // GET: Admin/Topic/Edit/5
        public ActionResult Edit(int? id)
        {
            var cities = db.cities.ToList();
            ViewBag.cities = cities;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ticket mticket = db.tickets.Find(id);
            if (mticket == null)
            {
                return HttpNotFound();
            }
            ViewBag.listticket = db.tickets.Where(m => m.status == 1).ToList();
            return View(mticket);
          
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ticket mticket)
        {
            var cities = db.cities.ToList();
            ViewBag.cities = cities;
            if (ModelState.IsValid)
            {
                HttpPostedFileBase file;
                file = Request.Files["airline"];
                string filename = file.FileName.ToString();
                if (filename.Equals("") == false)
                {
                   
                    var path = Path.Combine(Server.MapPath("~/Public/images/flight"), filename);
                 
                    file.SaveAs(path);
                    mticket.airline = filename;
                }
              
                  
                mticket.created_at = DateTime.Now;
                mticket.created_by = int.Parse(Session["Admin_id"].ToString());
                
                mticket.priceSale = mticket.price;
                mticket.updated_at = DateTime.Now;
                mticket.updated_by = int.Parse(Session["Admin_id"].ToString());
                db.Entry(mticket).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.listticket = db.tickets.Where(m => m.status ==1).ToList();
            return View(mticket);
        }


    }
}

BANVETAU/BANVETAU/Areas/Admin/Views/Tickets/Create.cshtml
@model BANVETAU.Models.ticket

@{
    ViewBag.Title = "Thêm Vé Tàu";
    Layout = "~/Areas/Admin/Views/Shared/_layOutAdmin.cshtml";
}


<div class="card card-title bg-white p-1">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Thêm Mới Vé Tàu </h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item"><a href="/Admin">Trang Chủ</a></li>
                <li class="breadcrumb-item active">Thêm Mới Vé Tàu</li>
            </ol>
        </div>
    </div>
</div>

<section class="@*container pt-2 card*@ card card-title bg-white p-1">
    @Html.Partial("_MessgeAlert")
    <div class="container bg-white pt-4 " style="margin-bottom:30px">

        @using (Html.BeginForm("Create", "Tickets", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class=" row ">
                <div class="col-md-4">  </div>
                <div class="col-md-4"> <h3 class="text-center font-weight-bold text-success "> Thêm Vé Tàu</h3> </div>
                <div class="col-md-4 ">
                    <div class="float-right">
                        <button class="btn btn-sm bg-success text-white"><i class="far fa-save"></i> Lưu</button>
                        <a href="~/admin/Tickets" class="btn btn-sm bg-danger text-white"><i class="far fa-window-close"></i> Hủy</a>
                    </div>
                </div>
            </div>
            <div class=" row ">
                <div class="col-md-10">
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Tên Vé Tàu</span></label>
                        <input type="text" name="name" class="form-control" value="" required />

                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Nội Dung Mô Tả</span></label>
                        <input type="text" name="description" class="form-control" value="" required />

                    </div>


                </div>
                <div class="col-md-5 ">

                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Từ Ga</span></label>
                        <select  name="fromAirport" class="selectpicker form-control" tabindex="1">

                            @foreach (var item in ViewBag.cities)
                            {
                                <option value="@item.cityId">@item.cityName</option>
                            }


                        </select>
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Đến Ga</span></label>
                        <select name="toAirport" class="selectpicker form-control" tabindex="1">

                            @foreach (var item in ViewBag.cities)
                            {
                                <option value="@item.cityId">@item.cityName</option>
                            }


                        </select>

                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Mã Tàu</span></label>
                        <input type="text" name="flightCode" class="form-control" value="" placeholder="" required />
                        <span asp-validation-for="flight" class="text-danger"></span>
                    </div>


                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Loại Ghế</span></label>
                        <select name="ticketType" class="selectpicker form-control" tabindex="1">
                            <option selected value="Promotion">Thường (Có Điều Hòa)</option>
                            <option value="Economic">Thường</option>
                            <option value="Bussiness">Thương Gia (Giường Nằm)</option>
                        </select>

                    </div>


                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Số Lượng Ghế</span></label>
                        <input type="number" name="guestTotal" class="form-control" value="" placeholder="Amount Seats > 50" required min="50" />
                        <span asp-validation-for="guestTotal" class="text-danger"></span>
                    </div>

                </div>
                <div class="col-md-5">
                    <div>

                        <label for="psw"><span class="text-secondary font-weight-bold">Ngày Đi</span></label>
                        <input type="date" name="departure_date" class="form-control" value="" required />
                     
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Thời Gian Đi</span></label>
                        <input type="time" name="departure_time" class="form-control" value="" required />
                       

                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Thời Gian Đến</span></label>
                        <input type="time" name="arrival_time" class="form-control" value="" required />
                      

                    </div>
                    @*<div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Airline</span></label>
                        <input type="file" class="form-control" name="airline" required />
                       
                    </div>*@
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Giá Vé</span></label>
                        <input type="number" name="price" class="form-control" placeholder="30$ <= Price <= 3000$" value="" required min="30" max="3000" />
                        <span asp-validation-for="price" class="text-danger"></span>
                    </div>
                        <div>
                            <label for="psw"><span class="text-secondary font-weight-bold">Hiển Thị</span></label>
                            <select name="status" class="selectpicker form-control" tabindex="1">
                                <option value="1">Hiển Thị</option>
                                <option value="2">Ẩn</option>
                            </select>
                        </div>
                    </div>
                </div>           
        }
    </div>
</section>

BANVETAU/BANVETAU/Areas/Admin/Views/Tickets/Edit.cshtml
@model BANVETAU.Models.ticket

@{
    ViewBag.Title = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_layOutAdmin.cshtml";
}


<div class="card card-title bg-white p-1">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Update Tickets </h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item"><a href="/Admin">Home</a></li>
                <li class="breadcrumb-item active">Update Tickets</li>
            </ol>
        </div>
    </div>
</div>

<section class="card card-title bg-white p-1">
    @Html.Partial("_MessgeAlert")
    <div class="container bg-white pt-4 " style="margin-bottom:30px">

        @using (Html.BeginForm("Edit", "Tickets", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class=" row ">
                <div class="col-md-4">  </div>
                <div class="col-md-4"> <h3 class="text-center font-weight-bold text-success "> Update Tickets</h3> </div>
                <div class="col-md-4 ">
                    <div class="float-right">
                        <button class="btn btn-sm bg-success text-white"><i class="far fa-save"></i> Save</button>
                        <a href="~/admin/Tickets" class="btn btn-sm bg-danger text-white"><i class="far fa-window-close"></i> Cancel</a>
                    </div>
                </div>
            </div>
            <div class=" row ">
                <div class="col-md-10">
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Ticket Title</span></label>

                        <input type="text" name="name" class="form-control" value="@Model.name" required />
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Ticket Description</span></label>
                        <input type="text" name="description" class="form-control" value="@Model.description" required />

                    </div>


                </div>
                <div class="col-md-5 ">

                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">From</span></label>
                        <select name="fromAirport" class="selectpicker form-control" tabindex="1">

                            @foreach (var item in ViewBag.cities)
                            {
                                <option value="@Model.city.cityId">@Model.city.cityName</option>
                                <option value="@item.cityId">@item.cityName</option>
                            }


                        </select>
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">To</span></label>
                        <select name="toAirport" class="selectpicker form-control" tabindex="1">

                            @foreach (var item in ViewBag.cities)
                            {
                                <option value="@Model.city1.cityId">@Model.city1.cityName</option>
                                <option value="@item.cityId">@item.cityName</option>
                            }


                        </select>

                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Flight Code</span></label>
                        <input type="text" name="flightCode" class="form-control" value="@Model.flightCode" placeholder="" required />
                        <span asp-validation-for="flight" class="text-danger"></span>
                    </div>


                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Class</span></label>
                        <select name="ticketType" class="selectpicker form-control" tabindex="1">
                            <option selected value="@Model.ticketType">@Model.ticketType</option>
                            <option value="Promotion">Promotion</option>
                            <option value="Economic">Economic</option>
                            <option value="Bussiness">Bussiness</option>
                        </select>

                    </div>


                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Amount Seats</span></label>
                        <input type="number" name="guestTotal" class="form-control" value="@Model.guestTotal" placeholder="Amount Seats > 50" required min="50" />
                        <span asp-validation-for="guestTotal" class="text-danger"></span>
                    </div>

                </div>
                <div class="col-md-5">
                    <div>

                        <label for="psw"><span class="text-secondary font-weight-bold">Start Date</span></label>
                            <input type="date" name="departure_date" class="form-control" value="@Model.departure_date.Value.ToString("yyyy-MM-dd")" />                      

                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Start Time</span></label>
                        <input type="time" name="departure_time" class="form-control" value="@Model.departure_time" required />


                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Arrive Time</span></label>
                        <input type="time" name="arrival_time" class="form-control" value="@Model.arrival_time" required />


                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Airline</span></label>
                        <input type="hidden" class="form-control" value="@Model.airline" name="airline" />
                        <input type="file" class="form-control"  name="airline" />

                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Price</span></label>
                        <input type="number" name="price" class="form-control" placeholder="30$ <= Price <= 3000$" value="@Model.price" required min="30" max="3000" />
                        <span asp-validation-for="price" class="text-danger"></span>
                    </div>
                    <div>
                        <label for="psw"><span class="text-secondary font-weight-bold">Status</span></label>
                        <select name="status" class="selectpicker form-control" tabindex="1">
                            <option value="1">Display</option>
                            <option value="2">Hidden</option>
                        </select>
                    </div>
                </div>
            </div>
        }
    </div>
</section>
<script>
    $("#form-search").submit(function (event) {
        $("#ngaybay").text("");
        $("#ngayve").text("");
        var ngaybay = $("#departure_date").val();
        var ngayve = $("#arrival_date").val();
        var typeticket = $("#ticketCheck").val();


        if (ngaybay == "Ngày Bay") {
            $("#ngaybay").text("Please select your flight date");

            return false;

        }
        if (typeticket == 2) {
            if (ngayve == "Ngày về") {
                $("#ngayve").text("Please select a return date");
                return false
            }
            else {
                return true;
            }
        }
        return true;

    });
    $(document).ready(function () {
        // By Default Disable radio button
        $("#arrival_date").attr('disabled', true);
        $("form input:radio").change(function () {
            if ($(this).val() == "enable") {
                $("#arrival_date").attr('disabled', false);
                $("#ticketCheck").val(2);
            }
            else {
                $("#arrival_date").attr('disabled', true);
                $("#ticketCheck").val(1);
            }
        });
    });
</script>

BANVETAU/BANVETAU/Areas/Admin/Views/Tickets/Index.cshtml
@model IEnumerable<BANVETAU.Models.ordersdetail>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layOutAdmin.cshtml";
}
<!-- Content Wrapper. Contains page content -->

<div class="card card-title bg-white p-1">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Quản Lý Vé </h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item m-0"><a href="~/Admin">Home</a></li>
                
            </ol>
        </div>
    </div>
</div>



<section class="">
    <div class=" bg-white card  p-3">
        <div class="row justify-content-end">
            <div class="col-md-3">
                <div class=" pt-1 ml-5">
                    <a class="text-white btn-sm btn-success" href="~/admin/Tickets/Create">Thêm Vé </a>
                    <a class="text-white btn-sm btn-danger " href="~/admin/Tickets/trash">Lịch Sử Xóa</a>
                 
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-9  w-100 ">
                @Html.Partial("_MessgeAlert")
            </div>
            <div class="col-md-12 p-3">

                <table id="myTable1" class="table  table-striped table-bordered dt-responsive nowrap">
                    <thead>
                        
                        <tr>
                            <th>MÃ Vé</th>
                            <th>Từ Ga</th>
                            <th>Đến Ga</th>
                            <th>Ngày Đi</th>
                            <th>Giá</th>
                            <th>Ghế</th>
                            <th>Thao Tác</th>

                        </tr>
                      
                    </thead>
                    <tbody>

                       
                            @foreach (var item in ViewBag.tickets)
                            {
                                string name = item.name;
                                <tr>
                                    <td class="text-cam">@item.id</td>
                                    <td>

                                        @item.city.cityName
                                    </td>
                                    <td width="15%">  @item.city1.cityName</td>
                                    <td style="font-size:14px;">@item.departure_date.ToString("dd/MM/yyyy")</td>
                                    <td style="font-size:14px;">@item.price.ToString("N0") $</td>
                                    <td style="font-size:14px;">Total @item.guestTotal - Booked @item.Sold</td>
                                    <td>
                                        @if (item.status == 1)
                                        {
                                            <a class="btn btn-sm btn-light text-success border a33" href="@Url.Action("Status", "Tickets", new { id = item.id })"> <i class="fas fa-toggle-on"></i> </a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-sm btn-light text-danger border a33" href="@Url.Action("Status", "Tickets", new { id = item.id })"> <i class="fas fa-toggle-off"></i> </a>
                                        }


                                      
                                            @if (item.Sold == 0)
                                            {
                                                <a class="btn btn-sm btn-light text-danger border" href="@Url.Action("Deltrash", "Tickets", new { id = item.id})">
                                                    <i class="fas fa-trash-alt"></i>
                                                </a>
                                           
                                        }
                                        <a class="btn btn-sm btn-light text-warning border" href="@Url.Action("Edit", "Tickets", new { id = item.id })">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                    </td>

                                </tr>
                            
                        }
                        </tbody>

                </table>
            </div>
        </div>
    </div>
</section>

BANVETAU/BANVETAU/Areas/Admin/Views/Tickets/Trash.cshtml
@model IEnumerable<BANVETAU.Models.ticket>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layOutAdmin.cshtml";
}
<!-- Content Wrapper. Contains page content -->

<div class="card card-title bg-white p-1">
    <div class="row">
        <div class="col-md-6 "> <h5 class="pl-2 mt-2 text-blues">Recycle Bin </h5> </div>
        <div class="col-md-6 m-0">
            <ol class="breadcrumb bg-white float-sm-right m-0">
                <li class="breadcrumb-item m-0"><a href="~/Admin">Home</a></li>
                <li class="breadcrumb-item active m-0">Recycle Bin</li>
            </ol>
        </div>
    </div>
</div>



<section class="">
    <div class=" bg-white card  p-3">
        <div class="row justify-content-end">
            <div class="col-md-3">
                <div class=" pt-1 ml-5">

                    <a class="text-white btn-sm btn-danger " href="~/admin/Tickets">CANCEL</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-9  w-100 ">
                @Html.Partial("_MessgeAlert")
            </div>
            <div class="col-md-12 p-3">

                <table id="myTable1" class="table  table-striped table-bordered dt-responsive nowrap">
                    <thead>

                        <tr>
                            <th>Airline</th>
                            <th>From</th>
                            <th>To</th>
                            <th>Start Date</th>
                            <th>Price</th>
                            <th>Function</th>
                            <th>Id</th>
                        </tr>

                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            string name = item.name;
                            <tr>

                                <td><img style="width:50px;" src="~/public/images/flight/@Html.DisplayFor(modelItem => item.airline)"></td>
                                <td>

                                    @item.city.cityName
                                </td>
                                <td width="15%">  @item.city1.cityName</td>
                                <td style="font-size:14px;">@item.departure_date.Value.ToString("dd/MM/yyyy")</td>
                                <td style="font-size:14px;">@item.price.Value.ToString("N0") $</td>
                                <td>
                                    <a class="btn btn-sm btn-light text-dark border" href="@Url.Action("Retrash", "Tickets", new { id = item.id })"> <i class="fas fa-undo"></i></a>
                                    <a class="btn btn-sm btn-light text-danger border" href="@Url.Action("deleteTrash", "Tickets", new { id = item.id })">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </td>
                                <td class="text-cam">@Html.DisplayFor(modelItem => item.id)</td>
                            </tr>
                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</section>